name: CI

on:
  push:
    branches:
      - web
  pull_request:
    branches:
      - web
  repository_dispatch:
    types: [code-updated]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout test-repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
